os: linux
dist: bionic
language: node_js
node_js:
  - 12

cache: npm

install:
  - npm install
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      npm install netlify-cli -g;
    fi

before_script:
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      npm run build;
    fi

script:
  - npm test

after_success:
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build;
    fi