[build.environment]
  REACT_APP_APP_VERSION = "1.2.3"
  REACT_APP_BACKEND_URL = "https://backend-flaskrestx.herokuapp.com/api/v1"
[context.production]
  [context.production.environment]
    ACCESS_TOKEN = "super secret"