export const LOADED_ACCOUNTS_LIST_SUCCESSFULLY = "LOADED_ACCOUNTS_LIST_SUCCESSFULLY";
export const LOADED_API_VERSION_SUCCESSFULLY = "LOADED_API_VERSION_SUCCESSFULLY";
export const TRY_LOADING = "TRY_LOADING";